### ISSUE TITLE
Analysis shapefile name in report legend doesn't match uploaded zip name

### ISSUE THREAD

**Issue by jessnoo** [Esri/environmental-impact#198]
The name shown in the report legend for a shapefile uploaded for analysis is "Override 1": 
![image](https://cloud.githubusercontent.com/assets/6181441/7028522/2d2ed7da-dd0b-11e4-8d60-0399fa4ac3e9.png)

Where is this configured in the app?

**Comment by CTLocalGovTeam** [comment]
@jessnoo The name for uploaded shape file is not configured in the app. 

Layer names are displayed in the legend based on how they are represented in the webmap json that is sent for printing. The uploaded shape file is represented as a feature collection in the webmap json. In case of feature collections, the print service defaults the name to "Override 1" as it was not able to read the feature collection name.

We have analyzed this and found a work around to achieve this using Unique value renderer. We add a unique value info with the shape file name as its label so that the legend for analysis shapefile gets displayed in the report.

We can describe this in more detail on the call.

**Comment by jessnoo** [comment]
@CTLocalGovTeam is the multipointLayer text a by product of the work around to get the zipped Shapefile name in the legend?

![image](https://cloud.githubusercontent.com/assets/6181441/7206616/0af3661a-e4e8-11e4-8952-bff4ffef9c76.png)

**Comment by jessnoo** [comment]
Verified in 1.3 with known issue #201
